name: publish-dockerhub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get the latest commit hash
        id: git_commit
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            quanttide/quanttide-docker-image-of-flutter:${{ steps.git_commit.outputs.short_sha }}
            quanttide/quanttide-docker-image-of-flutter:latest
